# -*- coding: utf-8 -*-
"""Summarization-Translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ELrknsloCoROtl_xcf0m8PP_x0T_OVBc

# Task 1 : Zero - shot Summarization
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name='google/flan-t5-base'
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

"""##Test the tokenizer encoding and decoding a simple sentence:"""

sentence = "علی: سلام، داداش! چطوری؟"

sentence_encoded = tokenizer(sentence, return_tensors='pt')

sentence_decoded = tokenizer.decode(
        sentence_encoded["input_ids"][0],
        skip_special_tokens=True
    )

print('ENCODED SENTENCE:')
print(sentence_encoded["input_ids"][0])
print('\nDECODED SENTENCE:')
print(sentence_decoded)

"""The model doesn't understand persian character at all. It seems that FLAN-T5 is trained mainly on English.
Its SentencePiece tokenizer doesn’t recognize Persian characters, so it turns them into generic unknown tokens. I use a multilingual model trained on persian too named "**facebook/mbart-large-50-many-to-many-mmt**"
"""

model_name_2 = "facebook/mbart-large-50-many-to-many-mmt"
tokenizer_2 = AutoTokenizer.from_pretrained(model_name_2, use_fast = True)
model_2 = AutoModelForSeq2SeqLM.from_pretrained(model_name_2)
tokenizer_2.tgt_lang = 'fa_IR'

sentence = "علی: سلام، داداش! چطوری؟"

sentence_encoded = tokenizer_2(sentence, return_tensors='pt')

sentence_decoded = tokenizer_2.decode(
        sentence_encoded["input_ids"][0],
        skip_special_tokens=True
    )

print('ENCODED SENTENCE:')
print(sentence_encoded["input_ids"][0])
print('\nDECODED SENTENCE:')
print(sentence_decoded)

"""We can see **facebook/mbart-large-50-many-to-many-mmt** will correctly tokenize Persian text and decode it back to the same string. Now it's time to explore how well this base LLM summarizes a dialogue without any prompt engineering."""

prompt = f"""
 Summarize the following Persian text in Persian:
علی: سلام، داداش! چطوری؟
محمد: سلام علی! خوبم، تو چطوری؟
علی: منم خوبم. این هفته قراره بریم فوتبال؟
محمد: آره، می‌خوام برم. ساعت چند؟
علی: ساعت ۵ تو پارک محل. بیا با هم بریم.
محمد: اوکی، منتظرت می‌مونم.
علی: بعد بازی می‌خوای بریم بستنی؟
محمد: آره، خیلی خوب میشه!
علی: پس شنبه همدیگه رو می‌بینیم.
محمد: حتماً، خداحافظ!
"""
# Set the beginning-of-sentence (BOS) token to Persian ("fa_IR") so that the model generates output in Persian.
model_2.config.forced_bos_token_id = tokenizer_2.lang_code_to_id["fa_IR"]

# Input constructed prompt instead of the dialogue.

inputs = tokenizer_2(prompt, return_tensors="pt")
output = tokenizer_2.decode(
        model_2.generate(
            inputs["input_ids"],
            max_new_tokens=100,
        )[0],
        skip_special_tokens=True
    )

print(f'Zero-Shot Summarization:\n{output}\n')

"""# Task 2 : Translation of the Dialogue"""

# Set source and target languages
tokenizer_2.src_lang = "fa_IR"   # Input is Persian
tokenizer_2.tgt_lang = "en_XX"   # Output should be English

# Persian dialogue
text = """
علی: سلام، داداش! چطوری؟
محمد: سلام علی! خوبم، تو چطوری؟
علی: منم خوبم. این هفته قراره بریم فوتبال؟
محمد: آره، می‌خوام برم. ساعت چند؟
علی: ساعت ۵ تو پارک محل. بیا با هم بریم.
محمد: اوکی، منتظرت می‌مونم.
علی: بعد بازی می‌خوای بریم بستنی؟
محمد: آره، خیلی خوب میشه!
علی: پس شنبه همدیگه رو می‌بینیم.
محمد: حتماً، خداحافظ!
"""

# 🔹 Prompt to translate the dialogue
prompt = f"Translate the following Persian dialogue to English:\n{text}"

# Tokenize input
inputs = tokenizer_2(prompt, return_tensors="pt")

# Set the BOS token to English so output starts in English
model_2.config.forced_bos_token_id = tokenizer_2.lang_code_to_id["en_XX"]

# Generate translation
output = model_2.generate(inputs["input_ids"], max_new_tokens=100)

# Decode and print
translation = tokenizer_2.decode(output[0], skip_special_tokens=True)
print("English Translation:\n", translation)

"""# Task 3 : Zero-Shot Persian Dialogue Summarization and Translation Using  **Mistral** model"""

from huggingface_hub import login
login()  # Paste your token when prompted

from transformers import AutoTokenizer, AutoModelForCausalLM
model_name_3 = "mistralai/Mistral-7B-v0.1"
tokenizer_3 = AutoTokenizer.from_pretrained(model_name_3, trust_remote_code=True)
model_3 = AutoModelForCausalLM.from_pretrained(model_name_3, trust_remote_code=True)

text = """
علی: سلام، داداش! چطوری؟
محمد: سلام علی! خوبم، تو چطوری؟
علی: منم خوبم. این هفته قراره بریم فوتبال؟
محمد: آره، می‌خوام برم. ساعت چند؟
علی: ساعت ۵ تو پارک محل. بیا با هم بریم.
محمد: اوکی، منتظرت می‌مونم.
علی: بعد بازی می‌خوای بریم بستنی؟
محمد: آره، خیلی خوب میشه!
علی: پس شنبه همدیگه رو می‌بینیم.
محمد: حتماً، خداحافظ!
"""

# ---- خلاصه‌سازی ----
prompt_summarize = "Summarize the following Persian dialogue in Persian:\n" + text

inputs2 = tokenizer_3(prompt_summarize, return_tensors="pt", truncation=True, max_length=512)

summary_ids = model_3.generate(
    **inputs2,
    max_new_tokens=80,
    num_beams=5,
    no_repeat_ngram_size=2,
    early_stopping=True
)
summary = tokenizer_3.decode(summary_ids[0], skip_special_tokens=True)
print("Summary (Mistral):", summary)

# ---- ترجمه به انگلیسی ----
prompt_translate = "Translate the following Persian dialogue into English:\n" + text

inputs = tokenizer_3(prompt_translate, return_tensors="pt", truncation=True, max_length=512)

translation_ids = model_3.generate(
    **inputs,
    max_new_tokens=100,
    num_beams=5,
    no_repeat_ngram_size=2,
    early_stopping=True
)
translation = tokenizer_3.decode(translation_ids[0], skip_special_tokens=True)
print("Translation (Mistral):", translation)