# -*- coding: utf-8 -*-
"""RAG PDF Question Answering with Enhanced Embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pzlm4j9d24SDCN0dz32KXGz47lUF-ES_

# RAG Q&A on PDFs with Enhanced Embeddings
"""

!pip install transformers
!pip install langchain[docarray]
!pip install docarray
!pip install pypdf
!pip install langchain_huggingface
!pip install bitsandbytes
!pip install langchain-community

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from transformers import BitsAndBytesConfig
import torch

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype="float16",
    bnb_4bit_quant_type="nf4"
)

tokenizer = AutoTokenizer.from_pretrained("unsloth/gemma-2-9b-it", use_fast=True)
model = AutoModelForCausalLM.from_pretrained(
    "unsloth/gemma-2-9b-it",
    device_map="auto",
    quantization_config=bnb_config,
    torch_dtype=torch.float16
)

text_gen = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=64
)

# Load the new pdf file
!gdown --id 1P_K5J4zsKpaxDw9lphU15X18qb5VcSdQ -O original.pdf
# Rename the downloaded file
!mv original.pdf new_doc.pdf

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("new_doc.pdf")
pages = loader.load_and_split()
print(len(pages))

from langchain_huggingface.llms import HuggingFacePipeline

llm = HuggingFacePipeline(pipeline=text_gen)

def apply_chat_template_and_response(prompt):
    messages = [
    {'role': 'user', 'content': prompt}
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=False
    )

    return llm.invoke(text).replace(text, '')

# from langchain.prompts import PromptTemplate
from langchain_core.prompts import PromptTemplate

template = """
You are a helpful and knowledgeable AI assistant. Use only the information retrieved from the documents to answer the user's question in Persian (Farsi). If the answer is not found in the retrieved context, respond with: "متاسفانه اطلاعاتی در این مورد ندارم." Do not use your own knowledge beyond the provided context. Be accurate, clear, and polite. Never mention the documents or the retrieval process in your response. Just respond naturally in Persian.
Context: {context}

Question: {question}

Answer:

"""

prompt = PromptTemplate.from_template(template)
prompt.format(context="Here is some context", question="Here is a question")

# from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_text_splitters import RecursiveCharacterTextSplitter


text_splitter = RecursiveCharacterTextSplitter(chunk_size=1024, chunk_overlap=256)
# text_documents = text_splitter.split_documents(pages)[:5]

pages

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=1024,
    chunk_overlap=256
)

docs = splitter.split_documents(pages)
len(docs)

from langchain_huggingface import HuggingFaceEmbeddings


embedding_name_1 = 'sbunlp/fabert'
embeddings_1 = HuggingFaceEmbeddings(
    model_name=embedding_name_1,
    # model_kwargs={"trust_remote_code": True},
)

from langchain_community.vectorstores import DocArrayInMemorySearch

from langchain_core.output_parsers import StrOutputParser

parser = StrOutputParser()

vectorstore_1 = DocArrayInMemorySearch.from_documents(docs, embedding=embeddings_1)
retriever_1= vectorstore_1.as_retriever()

query = "ملزومات پزشکی"
retriever = vectorstore_1.as_retriever()
retriever.invoke(query)

retrieved_context = retriever_1.invoke(query)

questions = [
    "این فایل درباره چیست؟",
    "چه نکات مهمی در این سند مطرح شده است؟",
    "هدف اصلی نویسندگان از تهیه این فایل چیست؟"
]

for question in questions:
    # Retrieve context from the vector store
    retrieved_context = retriever_1.invoke(question)

    # Join the content of retrieved documents
    context = "\n".join([d.page_content for d in retrieved_context])

    # Format the prompt with the retrieved context and the question
    formatted_prompt = prompt.format(context=context, question=question)

    # Generate response using your LLM function
    response_from_model = apply_chat_template_and_response(formatted_prompt)

    # Parse the response if you have a parser
    parsed_response = parser.parse(response_from_model)

    # Print question and answer
    print("🔹 سوال:", question)
    print("🔸 پاسخ:", parsed_response)
    print("-" * 70)

questions = [
    "تعریف قاچاق کالا و ارز"
]

for question in questions:
    retrieved_context = retriever_1.invoke(question)
    formatted_prompt = prompt.format(context=retrieved_context, question=question)
    response_from_model = apply_chat_template_and_response(formatted_prompt)
    parsed_response = parser.parse(response_from_model)

    print(f"Question: {question}")
    print(f"Answer: {parsed_response}")
    print()

questions = [
"دلایل اهمیت نظارت و برخورد با قاچاق "
]

for question in questions:
    retrieved_context = retriever_1.invoke(question)
    formatted_prompt = prompt.format(context=retrieved_context, question=question)
    response_from_model = apply_chat_template_and_response(formatted_prompt)
    parsed_response = parser.parse(response_from_model)

    print(f"Question: {question}")
    print(f"Answer: {parsed_response}")
    print()

questions = [
"پیامدهای اقتصادی ناشی از قاچاق"
]

for question in questions:
    retrieved_context = retriever_1.invoke(question)
    formatted_prompt = prompt.format(context=retrieved_context, question=question)
    response_from_model = apply_chat_template_and_response(formatted_prompt)
    parsed_response = parser.parse(response_from_model)

    print(f"Question: {question}")
    print(f"Answer: {parsed_response}")
    print()

questions = [
"رئوس مطالب"
]

for question in questions:
    retrieved_context = retriever_1.invoke(question)
    formatted_prompt = prompt.format(context=retrieved_context, question=question)
    response_from_model = apply_chat_template_and_response(formatted_prompt)
    parsed_response = parser.parse(response_from_model)

    print(f"Question: {question}")
    print(f"Answer: {parsed_response}")
    print()

"""In the first parT, I used the embedding model **sbunlp/fabert** to convert the PDF text into vector representations.

To improve the retrieval quality, I replaced the embedding model with **sentence-transformers/paraphrase-multilingual-mpnet-base-v2**. This model is multilingual and optimized for semantic similarity tasks.By using this model:

•	The retriever can find more relevant passages even if the exact words do not match the query.
•	Answers became more accurate and contextually appropriate.

After switching to this model (embedding_name_2 = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"), I reran the same three questions. The quality of the retrieved context improved, and the answers generated by the LLM were more precise and relevant.


"""

!pip install faiss-cpu

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

embedding_name_2 = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
embeddings_2 = HuggingFaceEmbeddings(model_name= embedding_name_2)

vectorstore_2 = FAISS.from_documents(docs, embeddings_2)
retriever_2 = vectorstore_2.as_retriever(search_kwargs={"k": 4})

questions = [
    "این فایل درباره چیست؟",
    "چه نکات مهمی در این سند مطرح شده است؟",
    "هدف اصلی نویسندگان از تهیه این فایل چیست؟"
]

for question in questions:
    # Retrieve context from the vector store
    retrieved_context = retriever_1.invoke(question)

    # Join the content of retrieved documents
    context = "\n".join([d.page_content for d in retrieved_context])

    # Format the prompt with the retrieved context and the question
    formatted_prompt = prompt.format(context=context, question=question)

    # Generate response using your LLM function
    response_from_model = apply_chat_template_and_response(formatted_prompt)

    # Parse the response if you have a parser
    parsed_response = parser.parse(response_from_model)

    # Print question and answer
    print("🔹 سوال:", question)
    print("🔸 پاسخ:", parsed_response)
    print("-" * 70)

questions = [
"پیامدهای اقتصادی ناشی از قاچاق"
]

for question in questions:
    retrieved_context = retriever_2.invoke(question)
    formatted_prompt = prompt.format(context=retrieved_context, question=question)
    response_from_model = apply_chat_template_and_response(formatted_prompt)
    parsed_response = parser.parse(response_from_model)

    print(f"Question: {question}")
    print(f"Answer: {parsed_response}")
    print()

questions = [
    "تعریف قاچاق کالا و ارز"
]

for question in questions:
    retrieved_context = retriever_2.invoke(question)
    formatted_prompt = prompt.format(context=retrieved_context, question=question)
    response_from_model = apply_chat_template_and_response(formatted_prompt)
    parsed_response = parser.parse(response_from_model)

    print(f"Question: {question}")
    print(f"Answer: {parsed_response}")
    print()

questions = [
"رئوس مطالب"
]

for question in questions:
    retrieved_context = retriever_2.invoke(question)
    formatted_prompt = prompt.format(context=retrieved_context, question=question)
    response_from_model = apply_chat_template_and_response(formatted_prompt)
    parsed_response = parser.parse(response_from_model)

    print(f"Question: {question}")
    print(f"Answer: {parsed_response}")
    print()

questions = [
"دلایل اهمیت نظارت و برخورد با قاچاق "
]

for question in questions:
    retrieved_context = retriever_2.invoke(question)
    formatted_prompt = prompt.format(context=retrieved_context, question=question)
    response_from_model = apply_chat_template_and_response(formatted_prompt)
    parsed_response = parser.parse(response_from_model)

    print(f"Question: {question}")
    print(f"Answer: {parsed_response}")
    print()

questions = [
"پیامدهای اقتصادی ناشی از قاچاق"
]

for question in questions:
    retrieved_context = retriever_2.invoke(question)
    formatted_prompt = prompt.format(context=retrieved_context, question=question)
    response_from_model = apply_chat_template_and_response(formatted_prompt)
    parsed_response = parser.parse(response_from_model)

    print(f"Question: {question}")
    print(f"Answer: {parsed_response}")
    print()